# Generated by Django 4.2.1 on 2023-08-11 18:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IconGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='iconPicker/icons/', validators=[django.core.validators.FileExtensionValidator(['svg'])])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pickers.icongroup')),
            ],
        ),
    ]
