# Generated by Django 4.2.1 on 2023-08-12 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='pickers.icongroup'),
        ),
    ]
