# Generated by Django 4.2.4 on 2025-04-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_category_menu_remove_item_menu_and_more'),
        ('pickers', '0002_alter_icon_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Icon',
            new_name='Asset',
        ),
        migrations.RenameModel(
            old_name='IconGroup',
            new_name='AssetGroup',
        ),
    ]
