# Generated by Django 4.2.4 on 2025-04-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickers', '0003_rename_icon_asset_rename_icongroup_assetgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetgroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
