# Generated by Django 5.2 on 2025-04-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickers', '0004_assetgroup_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='pickers.assetgroup'),
        ),
    ]
