# Generated by Django 4.2.1 on 2023-06-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='otp_code',
            new_name='OtpCode',
        ),
    ]
