# Generated by Django 4.2.1 on 2023-07-03 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_otpcode_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='code',
            new_name='password',
        ),
    ]
