# Generated by Django 4.2.4 on 2025-09-01 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('business', '0019_itembranch'),
        ('personnel', '0002_permission_remove_role_permissions_role_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='branches',
            field=models.ManyToManyField(blank=True, null=True, to='business.branch'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personnel', to=settings.AUTH_USER_MODEL),
        ),
    ]
