# Generated by Django 4.2.4 on 2025-09-02 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_personnel_branches_alter_personnel_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='business',
        ),
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
