# Generated by Django 4.2.4 on 2025-09-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_alter_personnel_is_active_alter_personnel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='invited_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='personnel',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.UniqueConstraint(fields=('business', 'invited_email'), name='unique_invite_per_business'),
        ),
    ]
