import "./globals.css";
import { cn } from "@/lib/utils";

import localFont from "next/font/local";
import React from "react";
import { Toaster } from "@/components/ui/sonner";

// Font files can be collocated inside of `app`
const vazir = localFont({
  src: "/fonts/Vazirmatn-RD[wght].woff2",
  display: "swap",
  variable: "--font-vazir",
});

export const metadata = {
  title: "menumaker | home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body
        className={cn(
          "overflow-x-hidden bg-white font-vazir font-medium",
          vazir.variable
        )}
      >
        <main data-vaul-drawer-wrapper>
          {children}
          <Toaster duration={4000} />
        </main>
      </body>
    </html>
  );
}
