import "./globals.css";

import localFont from "next/font/local";

// Font files can be colocated inside of `app`
const vazir = localFont({
  src: "/fonts/Vazirmatn-RD[wght].woff2",
  display: "swap",
  variable: "--font-vazir",
});

export const metadata = {
  title: "menumaker | home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${vazir.variable}`}>
      <body className="overflow-x-hidden bg-soft-blue font-vazir font-medium">
        {children}
      </body>
    </html>
  );
}
