# Generated by Django 4.2.1 on 2023-05-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='location',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
