# Generated by Django 4.2.4 on 2025-03-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_item_category_remove_item_menu_and_more'),
        ('pickers', '0002_alter_icon_group'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCategory',
            new_name='Category',
        ),
    ]
