# Generated by Django 4.2.4 on 2025-03-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_rename_itemcategory_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
