# Generated by Django 5.2 on 2025-07-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_remove_category_menu_remove_item_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='branch_structure',
            field=models.CharField(choices=[('single', 'single'), ('multiple', 'multiple')], default='single', max_length=20),
        ),
    ]
