# Generated by Django 5.2 on 2025-07-29 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_remove_business_branches_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
