# Generated by Django 4.2.4 on 2025-08-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='code',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
