# Generated by Django 4.2.4 on 2025-08-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_tablesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesession',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='business.table'),
        ),
    ]
