# Generated by Django 4.2.4 on 2025-08-12 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_tablesession_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 14, 52, 27, 932367, tzinfo=datetime.timezone.utc)),
        ),
    ]
