# Generated by Django 5.2 on 2025-08-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_tablesession_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesession',
            name='expires_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
