# Generated by Django 5.2 on 2025-08-13 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_alter_tablesession_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallWaiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='waiter_calls', to='business.tablesession')),
            ],
        ),
    ]
