# Generated by Django 5.2 on 2025-08-16 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_callwaiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='callwaiter',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
