# Generated by Django 4.2.4 on 2025-08-21 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0018_callwaiter_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.branch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_overrides', to='business.item')),
            ],
            options={
                'unique_together': {('item', 'branch')},
            },
        ),
    ]
