# Generated by Django 4.2.4 on 2025-10-12 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_itembranch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='child_bg',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_bg',
        ),
        migrations.RemoveField(
            model_name='category',
            name='text_color',
        ),
    ]
