# Generated by Django 4.2.4 on 2025-12-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_alter_reservation_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='number_of_guests',
            new_name='party_size',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_end',
            field=models.DateTimeField(blank=True),
        ),
    ]
