# Generated by Django 4.2.4 on 2025-12-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planduration',
            old_name='label',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('expired', 'Expired'), ('paused', 'Paused'), ('canceled', 'Canceled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='feature',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to='subscriptions.featurecategory'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.ManyToManyField(related_name='plans', through='subscriptions.PlanFeature', to='subscriptions.feature'),
        ),
    ]
