# Generated by Django 4.2.4 on 2025-03-28 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='itemcategory',
            name='menu',
        ),
        migrations.AlterField(
            model_name='menu',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='business.business'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='ItemCategory',
        ),
    ]
