# Generated by Django 4.2.4 on 2023-10-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickers', '0002_alter_icon_group'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='menu/<property object at 0x0000021B980C6250>/items/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_categories', to='pickers.icon'),
        ),
        migrations.AlterField(
            model_name='itemcategory',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categories', to='menu.menu'),
        ),
    ]
