# Generated by Django 4.2.4 on 2024-10-23 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuglobalstyling',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 10, 23, 17, 25, 45, 282487)),
        ),
    ]
