# Generated by Django 4.2.4 on 2024-10-23 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menuglobalstyling_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='bg_color',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price_unit',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='primary_color',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='secondary_color',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='tertiary_color',
        ),
        migrations.AlterField(
            model_name='menuglobalstyling',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 10, 23, 17, 27, 33, 572921)),
        ),
    ]
