# Generated by Django 5.2 on 2025-06-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_item_category_remove_item_menu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='primary_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/home/primary/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/home/secondary/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='tertiary_image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/home/tertiary/'),
        ),
    ]
