# Generated by Django 4.2.4 on 2024-10-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_menu_bg_color_remove_menu_price_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuglobalstyling',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
