# Generated by Django 5.2 on 2025-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_primary_image_menu_secondary_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='home_subtitle',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='home_title',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
