# Generated by Django 4.2.4 on 2023-10-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menu_menus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='menus',
            new_name='user',
        ),
    ]
