# Generated by Django 4.2.4 on 2023-10-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_rename_menus_menu_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcategory',
            old_name='item-category',
            new_name='menu',
        ),
    ]
