# Generated by Django 4.2.4 on 2023-11-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_item_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='price_unit',
            field=models.CharField(choices=[('simp', 'simple'), ('comp', 'compact'), ('engL', 'engLetter'), ('perL', 'perLetter')], default='simp', max_length=9),
        ),
    ]
