# Generated by Django 5.2 on 2025-06-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/'),
        ),
    ]
