# Generated by Django 4.2.4 on 2025-01-30 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_remove_menu_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='branch_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='menu',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menu',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='menu/images/logo/'),
        ),
        migrations.AddField(
            model_name='menu',
            name='phone_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='menu',
            name='primary_service_type',
            field=models.CharField(blank=True, choices=[('online', 'Online Order Only'), ('in_person', 'In-Person Only')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='service_type',
            field=models.CharField(choices=[('online', 'Online Order Only'), ('in_person', 'In-Person Only'), ('both', 'Both')], default='both', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='menu',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
