# Generated by Django 5.2 on 2025-06-05 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_menuimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.menu'),
        ),
    ]
