# Generated by Django 4.2.4 on 2023-12-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='exp_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='place',
            field=models.CharField(default='yes', max_length=150),
        ),
    ]
