# Generated by Django 4.2.4 on 2025-02-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_menu_branch_count_menu_created_menu_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='categories_display_type',
            field=models.CharField(choices=[('slider', 'Slider'), ('circular', 'Circular')], default='slider', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='item_page_type',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], default='horizontal', max_length=20),
        ),
        migrations.AddField(
            model_name='menu',
            name='search_item_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menu',
            name='waiter_request_is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuglobalstyling',
            name='border_radius',
            field=models.CharField(choices=[('sm', 'small'), ('md', 'medium'), ('lg', 'large')], default='full', max_length=2),
        ),
    ]
