# Generated by Django 4.2.4 on 2025-02-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_menu_categories_display_type_menu_item_page_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuglobalstyling',
            name='menu',
        ),
    ]
