# Generated by Django 5.2 on 2025-06-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuimage_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuimage',
            name='image',
            field=models.ImageField(default='', upload_to='menu/images/'),
            preserve_default=False,
        ),
    ]
