# Generated by Django 4.2.4 on 2023-12-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_table_created_table_exp_date_table_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='exp_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
