# Generated by Django 4.2.4 on 2025-11-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menuimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='cart_btn_display_type',
            field=models.CharField(choices=[('default', 'Compact'), ('default', 'Compact')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='menuglobalstyling',
            name='style',
            field=models.CharField(choices=[('default', 'Default'), ('retro', 'Retro')], default='default', max_length=20),
        ),
    ]
