# Generated by Django 4.2.4 on 2025-02-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_remove_menuglobalstyling_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuglobalstyling',
            name='menu',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu'),
        ),
    ]
