# Generated by Django 4.2.4 on 2024-01-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_alter_table_created_alter_table_exp_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='user',
            new_name='owner',
        ),
    ]
