# Generated by Django 4.2.4 on 2025-11-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menu_cart_btn_display_type_menuglobalstyling_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='cart_btn_display_type',
            field=models.CharField(choices=[('default', 'Default'), ('compact', 'Compact')], default='default', max_length=20),
        ),
    ]
