# Generated by Django 4.2.4 on 2025-02-12 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0009_menuglobalstyling_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('name_en', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('service_type', models.CharField(choices=[('online', 'Online Order Only'), ('in_person', 'In-Person Only'), ('both', 'Both')], default='both', max_length=20)),
                ('primary_service_type', models.CharField(blank=True, choices=[('online', 'Online Order Only'), ('in_person', 'In-Person Only')], max_length=20, null=True)),
                ('branch_count', models.PositiveIntegerField(default=1)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('phone_numbers', models.JSONField(blank=True, default=list)),
                ('locations', models.JSONField(blank=True, default=list)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
