# Generated by Django 4.2.4 on 2025-02-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.business'),
        ),
    ]
