# Generated by Django 4.2.4 on 2024-01-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_rename_user_menu_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
