# Generated by Django 4.2.4 on 2025-11-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_alter_menu_cart_btn_display_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuglobalstyling',
            name='unit_display_type',
            field=models.CharField(choices=[('default', 'Default (250,000 تومان)'), ('compact', 'Compact (250 هزار تومان)'), ('persian_abbr', 'Persian Abbreviated (250,000 ت)'), ('english_abbr', 'English Abbreviated (250,000 T)')], default='default', max_length=12),
        ),
    ]
