# Generated by Django 4.2.4 on 2025-02-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menu_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='branch_count',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='personnel',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='phone_numbers',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='primary_service_type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='social_links',
        ),
        migrations.AlterField(
            model_name='menu',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='menu.business'),
        ),
    ]
