# Generated by Django 4.2.4 on 2024-01-26 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_menu_name_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name_id',
            new_name='menu_id',
        ),
    ]
