# Generated by Django 4.2.4 on 2025-11-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_menuglobalstyling_unit_display_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='items_display_type',
            field=models.CharField(choices=[('full-bleed-overlay', 'Full-Bleed with Overlay'), ('half-image-stacked', 'Half-Image Stacked')], default='half-image-stacked', max_length=20),
        ),
    ]
