# Generated by Django 4.2.4 on 2024-01-26 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_rename_name_id_menu_menu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_id',
            field=models.CharField(default='venhan', max_length=100, unique=True),
        ),
    ]
