# Generated by Django 4.2.4 on 2024-05-05 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0013_alter_item_price_alter_menu_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='personnel',
            field=models.ManyToManyField(related_name='places', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/items/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu'),
        ),
    ]
