# Generated by Django 4.2.4 on 2025-02-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_rename_locations_business_branches_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuglobalstyling',
            old_name='click_animation',
            new_name='click_animation_type',
        ),
        migrations.AddField(
            model_name='menuglobalstyling',
            name='click_animation_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
