# Generated by Django 4.2.4 on 2025-03-06 16:12

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_rename_click_animation_menuglobalstyling_click_animation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuglobalstyling',
            name='border_radius',
            field=models.CharField(choices=[('sm', 'small'), ('md', 'medium'), ('lg', 'large'), ('full', 'full')], default='full', max_length=4),
        ),
        migrations.AlterField(
            model_name='menuglobalstyling',
            name='click_animation_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ripple', 'ripple effect'), ('tactile', 'tactile effect')], max_length=14, null=True),
        ),
    ]
