# Generated by Django 4.2.4 on 2024-05-05 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0014_menu_personnel_alter_item_image_alter_item_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_places', to=settings.AUTH_USER_MODEL),
        ),
    ]
