# Generated by Django 4.2.4 on 2025-03-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_menuglobalstyling_border_radius_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='name_en',
            field=models.CharField(default='business name', max_length=100),
        ),
    ]
