# Generated by Django 4.2.4 on 2024-06-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_menu_slug_alter_menu_menu_id_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='name_en',
            field=models.CharField(default='', max_length=100),
        ),
    ]
