# Generated by Django 4.2.4 on 2024-06-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_menu_name_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
    ]
